Portfolio/Controllers/AdminController.cs
using Portfolio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.Controllers
{
    public class AdminController : Controller
    {
        MyPortfolioDbEntities context=new MyPortfolioDbEntities();
        
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialSideBar() 
        {
            ViewBag.imageUrl = context.About.Select(x => x.ImageUrl).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }

        public PartialViewResult PartialSocialMedia()
        {
            return PartialView();
        }
        public ActionResult DownloadCV()
        {
            // Dosya yolunu kontrol edin
            var filePath = Server.MapPath("~/Content/images/AHMETBATUHANAVCIOGLURESUME.pdf");

            // Eğer dosya yoksa bir hata döndür
            if (!System.IO.File.Exists(filePath))
            {
                return HttpNotFound("Dosya bulunamadı.");
            }

            var fileName = "AHMETBATUHANAVCIOGLURESUME.pdf";
            var contentType = "image/jpeg/pdf";

            // Dosya indirilebilir olarak döndür
            return File(filePath, contentType, fileName);
        }
    }
}

Portfolio/Controllers/DefaultController.cs
using Portfolio.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Portfolio.Controllers
{
    public class DefaultController : Controller
    {
        MyPortfolioDbEntities context=new MyPortfolioDbEntities();
        public ActionResult Index()
        {
            List<SelectListItem> values=(from x in context.Category.ToList()
                                         select new SelectListItem
                                         {
                                             Text=x.CategoryName,
                                             Value=x.CategoryId.ToString()
                                         }).ToList();
            ViewBag.v=values;
            return View();
        }

        [HttpPost]
        public ActionResult Index(Message message)
        {
            message.SendDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            message.IsRead = false;
            context.Message.Add(message);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult PartialHead()
        {
            return PartialView();
        }

        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }

        public PartialViewResult PartialHeader()
        {
            ViewBag.title=context.About.Select(x=>x.Title).FirstOrDefault();
            ViewBag.detail=context.About.Select(x=>x.Detail).FirstOrDefault();
            ViewBag.image=context.About.Select(x=>x.ImageUrl).FirstOrDefault();

            ViewBag.address=context.Profile.Select(x=>x.Address).FirstOrDefault();
            ViewBag.email=context.Profile.Select(x=>x.Email).FirstOrDefault();
            ViewBag.phone=context.Profile.Select(x=>x.PhoneNumber).FirstOrDefault();
            ViewBag.github=context.Profile.Select(x=>x.Github).FirstOrDefault();
       
            return PartialView();
        }

        public PartialViewResult PartialAbout()
        {
            ViewBag.title = context.Profile.Select(x => x.Title).FirstOrDefault();
            ViewBag.description = context.Profile.Select(x => x.Description).FirstOrDefault();
            ViewBag.phone = context.Profile.Select(x => x.PhoneNumber).FirstOrDefault();
            ViewBag.email = context.Profile.Select(x => x.Email).FirstOrDefault();
            ViewBag.image = context.Profile.Select(x => x.ImageUrl).FirstOrDefault();

            return PartialView();
        }

        public PartialViewResult PartialEducation()
        {
            var value = context.Education.ToList();
            return PartialView(value);
        }

        public PartialViewResult PartialScript()
        {
            return PartialView();
        }

        public PartialViewResult PartialSkill()
        {
            var values= context.Skill.ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialSocialMedia()
        {
            var values = context.SocialMedia.Where(x => x.Status == true).ToList();
            return PartialView(values);
        }

        public PartialViewResult PartialTestimonial(Testimonial t)
        {
            ViewBag.name=context.Testimonial.Select(x=>x.Name).FirstOrDefault();
            ViewBag.title=context.Testimonial.Select(x=>x.Title).FirstOrDefault();
            ViewBag.comment=context.Testimonial.Select(x=>x.Comment).FirstOrDefault();
            ViewBag.ImageUrl=context.Testimonial.Select(x=>x.ImageUrl).FirstOrDefault();
            
            return PartialView();
        }

        public PartialViewResult PartialExperience()
        {
            ViewBag.companyName=context.Experience.Select(x=>x.CompanyName).FirstOrDefault();
            ViewBag.workDate=context.Experience.Select(x=>x.WorkDate).FirstOrDefault();
            ViewBag.title=context.Experience.Select(x=>x.Title).FirstOrDefault();
            ViewBag.description=context.Experience.Select(x=>x.Description).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialServices()
        {
            ViewBag.title=context.Service.Select(x=>x.Title).FirstOrDefault();
            ViewBag.description=context.Service.Select(x=>x.Description).FirstOrDefault();
            ViewBag.icon=context.Service.Select(x=>x.Icon).FirstOrDefault();
            return PartialView();
        }

        public PartialViewResult PartialPortfolio()
        {
            var values=context.Portfolio.ToList();
            return PartialView(values);
        }
        
    }
}

Portfolio/Views/Default/Index.cshtml
@model Portfolio.Models.Message
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

@Html.Action("PartialHead", "Default")

<body>

    <!-- Spinner Start -->
    <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
        <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <!-- Spinner End -->
    <!-- Navbar Start -->
    @Html.Action("PartialNavbar", "Default")
    <!-- Navbar End -->
    <!-- Header Start -->
    @Html.Action("PartialHeader", "Default")
    <!-- Header End -->
    <!-- About Start -->
    @Html.Action("PartialAbout", "Default")
    <!-- About End -->
    <!-- Education Start -->
    @Html.Action("PartialEducation", "Default")
    <!-- Education End -->
    <!-- Experience Start -->
    @Html.Action("PartialExperience","Default")
    <!-- Exparience End -->
    <!-- Skills Start -->
    @Html.Action("PartialSkill", "Default")
    <!-- Skills End -->
    <!-- Service Start -->
    @Html.Action("PartialServices","Default")
    <!-- Service End -->
    <!-- Portfolio Start -->
    @Html.Action("PartialPortfolio","Default")
    <!-- Portfolio End -->
    <!-- Testimonial Start -->
    @Html.Action("PartialTestimonial", "Default")
    <!-- Testimonial End -->
    <!-- Contact Start -->
    <div class="container-fluid" id="pigraContact">
        <div class="container">
            <div class="row g-0">
                @Html.Action("PartialContactSideBar", "Contact")
                <div class="col-lg-9">
                    <div class="contact-content h-100 pt-6 ps-6 pb-6">
                        <div class="bg-light p-4">
                            <div class="row g-5">
                                @Html.Action("PartialContactAddress", "Contact")
                                <div class="col-xl-7 wow fadeInUp" data-wow-delay="0.3s">
                                    <div>
                                        <form>
                                            <div class="row g-3">
                                                <div class="col-lg-12 col-xl-6">
                                                    <div class="form-floating">
                                                        <input type="text" class="form-control border-0" id="name" placeholder="adınız soyadınız" name="Name">
                                                        <label for="name">Adınız</label>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-xl-6">
                                                    <div class="form-floating">
                                                        <input type="email" class="form-control border-0" id="email" placeholder="Email Adresiniz" name="Email">
                                                        <label for="email">Email Adresi</label>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-xl-6">
                                                    <div class="form-floating">
                                                        <input type="phone" class="form-control border-0" id="phone" placeholder="Telefon Numaranız" name="PhoneNumber">
                                                        <label for="phone">Telefon</label>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 col-xl-6">
                                                    <div class="form-floating">
                                                        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.v, new { @class = "form-control" })
                                                        <label for="project">Konu</label>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-floating">
                                                        <input type="text" class="form-control border-0" id="subject" placeholder="Konu Başlığı" name="Subject">
                                                        <label for="subject">Konu Başlığı</label>
                                                    </div>
                                                </div>
                                                <div class="col-12">
                                                    <div class="form-floating">
                                                        <textarea class="form-control border-0" placeholder="Mesajınızı Yazın" id="message" style="height: 120px" name="MessageDetail"></textarea>
                                                        <label for="message">Mesaj</label>
                                                    </div>

                                                </div>
                                                <div class="col-12">
                                                    <button class="btn btn-primary w-100 py-3">Mesajı Gönder</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                @Html.Action("PartialContactLocation", "Contact")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
    <!-- Footer Start -->
    @Html.Action("PartialSocialMedia", "Default")
    <!-- Footer End -->
    <!-- Back to Top -->
    @Html.Action("PartialScript", "Default")
</body>
</html>

Portfolio/Views/Default/PartialAbout.cshtml
<div class="container-fluid" id="pigraAbout">
    <div class="container">
        <div class="row g-0">
            <div class="col-12 col-lg-3">
                <div class="about-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Hakkımda</p>
                        <h1 class="display-6 text-white mb-0">Bilgisayar Mühendisi/ Junior Full Stack Developer</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-9">
                <div class="about-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-5">
                        <div class="col-xl-5">
                            <div class="about-img bg-light p-4 wow fadeInUp" data-wow-delay="0.1s">
                                <img src="@ViewBag.image" class="img-fluid w-100" alt="Image">
                                <div class="sosial-icon">
                                    <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-facebook-f text-white"></i></a>
                                    <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-twitter text-white"></i></a>
                                    <a class="btn btn-primary btn-sm-square mb-3" href="#"><i class="fab fa-instagram text-white"></i></a>
                                    <a class="btn btn-primary btn-sm-square mb-0" href="#"><i class="fab fa-linkedin-in text-white"></i></a>
                                </div>
                            </div>
                        </div>
                        <div class="col-xl-7 wow fadeInUp" data-wow-delay="0.3s">
                            <h4 class="mb-4">@ViewBag.title</h4>
                            <p class="mb-4">
                                @ViewBag.description                            </p>
                            
                            <a href="@Url.Action("DownloadCV", "Admin")" class="btn btn-primary py-2 px-4"> <i class="fas fa-download me-2"></i>CV mi İndirin</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/Views/Default/PartialEducation.cshtml
@model List<Portfolio.Models.Education>  

<div class="container-fluid" id="pigraEducation">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="education-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Eğitim</p>
                        <h1 class="display-6 text-white mb-0">Lisans ve Diğer Eğitimlerim</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="education-content h-100 pt-6 ps-6 pb-6">
                    @foreach (var item in Model)
                    {
                        <div class="row g-4">
                            <div class="col-12">
                                <div class="education-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                    <div class="d-flex align-items-center mb-3">
                                        <p class="fs-5 mb-0 me-4">@item.Title</p>
                                        <div>
                                            <span class="fa fa-calendar me-1"></span> @item.EducationDate
                                        </div>
                                    </div>
                                    <h4 class="mb-3">@item.Subtitle</h4>
                                    <p class="mb-0">
                                        @item.Description                                       
                                    </p>
                                </div>
                            </div>

                        </div>
                        <br />
                    }


                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/Views/Default/PartialExperience.cshtml
<div class="container-fluid">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="experience-header bg-dark h-100 pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Deneyimler</p>
                        <h1 class="display-6 text-white mb-0">İş Deneyimlerim</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="experience-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4">
                        <div class="col-12">
                            <div class="experience-item rounded p-4 h-100 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="d-flex align-items-center mb-3">
                                    <p class="fs-5 mb-0 me-4">@ViewBag.companyName</p>
                                    <div>
                                        <span class="fa fa-calendar me-1"></span> @ViewBag.workDate
                                    </div>
                                </div>
                                <h4 class="mb-3">@ViewBag.title</h4>
                                <p class="mb-0">
                                    @ViewBag.description
                                </p>
                            </div>
                        </div>
                        
                  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/Views/Default/PartialHead.cshtml
<head>
    <meta charset="utf-8">
    <title>Kişisel Portfolyo</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Edu+TAS+Beginner:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link rel="stylesheet" href="/Content/Pigra-1.0.0/lib/animate/animate.min.css" />
    <link href="/Content/Pigra-1.0.0/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="/Content/Pigra-1.0.0/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">


    <!-- Customized Bootstrap Stylesheet -->
    <link href="/Content/Pigra-1.0.0/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/Content/Pigra-1.0.0/css/style.css" rel="stylesheet">
</head>

Portfolio/Views/Default/PartialHeader.cshtml
<div class="container-fluid" id="pigraHome">
    <div class="container">
        <div class="row g-0">
            <div class="col-12 col-lg-3">
                <div class="header-content bg-dark h-100 pt-6 pe-6 pb-6">
                    <a href="index.html" class="navbar-brand d-inline-flex pb-5 wow fadeInUp" data-wow-delay="0.1s">
                        <h1 class="display-6 text-white mb-0">Portfolyo</h1>
                    </a>
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.3s">
                        <p class="text-white sub-title">👋 Merhaba Ben Ahmet Batuhan Avcıoğlu</p>
                        <h1 class="display-6 text-white mb-0">Bilgisayar Mühendisi</h1>
                    </div>
                </div>
            </div>
            <div class="col-12 col-lg-9">
                <div class="header-img d-flex h-100 pt-6 ps-6 pb-6">
                    <div class="row g-5">
                        <div class="col-xl-6 wow fadeInUp" data-wow-delay="0.1s">
                            <div class="bg-light p-4" style="border-radius: 68% 32% 100% 0% / 0% 75% 25% 100%;">
                                <img src="~/Content/images/pp.jpg" class="img-fluid w-100" style="border-radius: 68% 32% 100% 0% / 0% 75% 25% 100%;" alt="Image">
                            </div>
                        </div>
                        <div class="col-xl-6 wow fadeInUp" data-wow-delay="0.3s">
                            <h1 class="display-6 mb-4">@ViewBag.title</h1>
                            <p class="mb-4">
                                @ViewBag.detail
                            </p>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fas fa-map-marker-alt text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.address</p>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fas fa-envelope text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.email</p>
                            </div>
                            <div class="d-flex align-items-center mb-2">
                                <i class="fa fa-phone-alt text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.phone</p>
                            </div>
                            <div class="d-flex align-items-center mb-4">
                                <i class="fab fa-firefox-browser text-primary me-3"></i>
                                <p class="text-dark mb-0">@ViewBag.github</p>
                            </div>
                            <div class="d-flex">
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-facebook-f text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-twitter text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-3" href="#"><i class="fab fa-instagram text-white"></i></a>
                                <a class="btn btn-primary btn-sm-square me-0" href="https://www.linkedin.com/in/ahmet-batuhan-avc%C4%B1o%C4%9Flu-002906184/"><i class="fab fa-linkedin-in text-white"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/Views/Default/PartialNavbar.cshtml
<div class="container-fluid nav-section border-0">
    <nav class="navbar navbar-light">
        <div class="navbar-nav flex-column">
            <a href="#pigraHome" class="nav-item nav-link active"><span class="fa fa-home"></span> Anasayfa</a>
            <a href="#pigraAbout" class="nav-item nav-link"><span class="far fa-address-card"></span> Hakkımda</a>
            <a href="#pigraEducation" class="nav-item nav-link"><span class="fas fa-school"></span> Eğitim Hayatım</a>
            <a href="#pigraExperience" class="nav-item nav-link"><span class="fas fa-laptop"></span> Deneyimlerim</a>
            <a href="#pigraSkill" class="nav-item nav-link"><span class="fas fa-glasses"></span> Yeteneklerim</a>
            <a href="#pigraService" class="nav-item nav-link"><span class="fab fa-servicestack"></span> Hizmetlerim</a>
            <a href="#pigraPortfolio" class="nav-item nav-link"><span class="fas fa-pencil-alt"></span> Portfolyo</a>
            <a href="#pigraTestimonial" class="nav-item nav-link"><span class="fas fa-lightbulb"></span> Referanslarım</a>
            <a href="#pigraContact" class="nav-item nav-link"><span class="fas fa-address-book"></span> Bana Yazın</a>
        </div>
    </nav>
</div>

Portfolio/Views/Default/PartialPortfolio.cshtml
@model List<Portfolio.Models.Portfolio>
<div class="container-fluid">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="portfolio-header h-100 bg-dark pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Portfolio</p>
                        <h1 class="display-6 text-white mb-0">Projelerim</h1>
                    </div>
                </div>
            </div>
            
                <div class="col-lg-9">
                    <div class="portfolio-content h-100 pt-6 ps-6 pb-6">
                        <div class="portfolio-item py-5 border-bottom wow fadeInUp" data-wow-delay="0.1s">
                            @foreach (var item in Model)
                            {
                                <div class="row g-4 align-items-center">

                                    <div class="col-xl-6">
                                        <h4 class="text-body">@item.Name</h4>
                                        <h1 class="display-6 mb-0">@item.Description</h1>
                                    </div>
                                    <div class="col-9 col-xl-4">
                                        <div class="portfolio-img">
                                            <div class="portfolio-img-inner">
                                                <img src="@item.ImageUrl" class="img-fluid" alt="Image">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-3 col-xl-2">
                                        <div class="view-img">
                                            <a href="@item.ImageUrl" class="btn btn-primary btn-lg-square" data-lightbox="Portfolio-1"><i class="fas fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            }
                            </div>

                    </div>
                </div>
            

        </div>
    </div>
</div>

Portfolio/Views/Default/PartialScript.cshtml
<a href="#" class="btn btn-primary btn-lg-square back-to-top"><i class="fa fa-arrow-up"></i></a>


<!-- JavaScript Libraries -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/wow/wow.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/easing/easing.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/waypoints/waypoints.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/counterup/counterup.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/lightbox/js/lightbox.min.js"></script>
<script src="/Content/Pigra-1.0.0/lib/owlcarousel/owl.carousel.min.js"></script>


<!-- Template Javascript -->
<script src="/Content/Pigra-1.0.0/js/main.js"></script>

Portfolio/Views/Default/PartialServices.cshtml
<div class="container-fluid" id="pigraService">
    <div class="container">
        <div class="row g-0">
            <div class="col-lg-3">
                <div class="service-header h-100 bg-dark pt-6 pe-6 pb-6">
                    <div class="text-start d-flex flex-column justify-content-center wow fadeInUp" data-wow-delay="0.1s">
                        <p class="text-white sub-title">Hizmetlerim</p>
                        <h1 class="display-6 text-white mb-0">Neler Yapabilirim ?</h1>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="service-content h-100 pt-6 ps-6 pb-6">
                    <div class="row g-4">
                        <div class="col-12">
                            <div class="service-item p-4 wow fadeInUp" data-wow-delay="0.1s">
                                <div class="row g-4 align-items-center">
                                    <div class="col-xl-2">
                                        <i class="@ViewBag.icon"></i>
                                    </div>
                                    <div class="col-xl-3">
                                        <a href="#" class="h4 mb-0">@ViewBag.title</a>
                                    </div>
                                    <div class="col-xl-4">
                                        <p class="mb-0">
                                        @ViewBag.description
                                        </p>
                                    </div>
                                    <div class="col-xl-3">
                                        <p><i class="fa fa-check me-2"></i> UI/UX Design</p>
                                        <p><i class="fa fa-check me-2"></i> Research</p>
                                        <p class="mb-0"><i class="fa fa-check me-2"></i> Mobile App</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>